# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'form.ui'
##
## Created by: Qt User Interface Compiler version 6.6.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QGroupBox, QLabel,
    QMainWindow, QMenuBar, QPlainTextEdit, QPushButton,
    QSizePolicy, QStatusBar, QTextBrowser, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1920, 1080)
        MainWindow.setMinimumSize(QSize(1024, 720))
        font = QFont()
        font.setPointSize(11)
        font.setBold(False)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet(u"")
        self.actiondate = QAction(MainWindow)
        self.actiondate.setObjectName(u"actiondate")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.line = QFrame(self.centralwidget)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(150, 90, 20, 941))
        self.line.setLineWidth(1)
        self.line.setFrameShape(QFrame.VLine)
        self.line.setFrameShadow(QFrame.Sunken)
        self.line_2 = QFrame(self.centralwidget)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setGeometry(QRect(0, 90, 1920, 3))
        self.line_2.setFrameShape(QFrame.HLine)
        self.line_2.setFrameShadow(QFrame.Sunken)
        self.Tools = QGroupBox(self.centralwidget)
        self.Tools.setObjectName(u"Tools")
        self.Tools.setGeometry(QRect(10, 140, 141, 181))
        font1 = QFont()
        font1.setFamilies([u"Consolas"])
        font1.setPointSize(11)
        font1.setBold(True)
        self.Tools.setFont(font1)
        self.squareBox = QPushButton(self.Tools)
        self.squareBox.setObjectName(u"squareBox")
        self.squareBox.setGeometry(QRect(10, 40, 120, 24))
        icon = QIcon()
        icon.addFile(u"assets/Icons/square.png", QSize(), QIcon.Normal, QIcon.Off)
        self.squareBox.setIcon(icon)
        self.squareBox.setIconSize(QSize(20, 20))
        self.boundingBoxLabel = QLabel(self.Tools)
        self.boundingBoxLabel.setObjectName(u"boundingBoxLabel")
        self.boundingBoxLabel.setGeometry(QRect(10, 20, 81, 20))
        font2 = QFont()
        font2.setFamilies([u"Consolas"])
        font2.setPointSize(9)
        font2.setBold(True)
        font2.setUnderline(False)
        self.boundingBoxLabel.setFont(font2)
        self.rhombusBoxLabel = QLabel(self.Tools)
        self.rhombusBoxLabel.setObjectName(u"rhombusBoxLabel")
        self.rhombusBoxLabel.setGeometry(QRect(10, 70, 81, 16))
        font3 = QFont()
        font3.setFamilies([u"Consolas"])
        font3.setPointSize(9)
        font3.setBold(True)
        self.rhombusBoxLabel.setFont(font3)
        self.rhombusBox = QPushButton(self.Tools)
        self.rhombusBox.setObjectName(u"rhombusBox")
        self.rhombusBox.setGeometry(QRect(10, 90, 120, 24))
        icon1 = QIcon()
        icon1.addFile(u"assets/Icons/rhomb-outline.png", QSize(), QIcon.Normal, QIcon.Off)
        self.rhombusBox.setIcon(icon1)
        self.rhombusBox.setIconSize(QSize(20, 20))
        self.findCenter = QLabel(self.Tools)
        self.findCenter.setObjectName(u"findCenter")
        self.findCenter.setGeometry(QRect(10, 120, 81, 16))
        self.findCenter.setFont(font3)
        self.cntrBtn = QPushButton(self.Tools)
        self.cntrBtn.setObjectName(u"cntrBtn")
        self.cntrBtn.setEnabled(True)
        self.cntrBtn.setGeometry(QRect(10, 140, 121, 24))
        self.cntrBtn.setAutoFillBackground(False)
        icon2 = QIcon()
        icon2.addFile(u"assets/Icons/center.png", QSize(), QIcon.Normal, QIcon.Off)
        self.cntrBtn.setIcon(icon2)
        self.cntrBtn.setIconSize(QSize(20, 20))
        self.cntrBtn.setCheckable(True)
        self.OrgImg = QGroupBox(self.centralwidget)
        self.OrgImg.setObjectName(u"OrgImg")
        self.OrgImg.setGeometry(QRect(170, 90, 551, 411))
        font4 = QFont()
        font4.setFamilies([u"Consolas"])
        font4.setPointSize(12)
        font4.setBold(True)
        self.OrgImg.setFont(font4)
        self.orgImageDisp = QLabel(self.OrgImg)
        self.orgImageDisp.setObjectName(u"orgImageDisp")
        self.orgImageDisp.setGeometry(QRect(10, 30, 531, 371))
        self.orgImageDisp.setPixmap(QPixmap(u"Icons/noImageAvailable.png"))
        self.orgImageDisp.setScaledContents(True)
        self.line_3 = QFrame(self.centralwidget)
        self.line_3.setObjectName(u"line_3")
        self.line_3.setGeometry(QRect(160, 600, 1761, 20))
        self.line_3.setFrameShape(QFrame.HLine)
        self.line_3.setFrameShadow(QFrame.Sunken)
        self.line_4 = QFrame(self.centralwidget)
        self.line_4.setObjectName(u"line_4")
        self.line_4.setGeometry(QRect(720, 90, 20, 521))
        self.line_4.setFrameShape(QFrame.VLine)
        self.line_4.setFrameShadow(QFrame.Sunken)
        self.groupBox_3 = QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(10, 90, 141, 51))
        self.groupBox_3.setFont(font1)
        self.loadFile = QPushButton(self.groupBox_3)
        self.loadFile.setObjectName(u"loadFile")
        self.loadFile.setGeometry(QRect(10, 20, 120, 24))
        self.loadFile.setFont(font3)
        icon3 = QIcon()
        icon3.addFile(u"assets/Icons/icons8-folder-50.png", QSize(), QIcon.Normal, QIcon.Off)
        self.loadFile.setIcon(icon3)
        self.loadFile.setIconSize(QSize(24, 24))
        self.clearGrp = QGroupBox(self.centralwidget)
        self.clearGrp.setObjectName(u"clearGrp")
        self.clearGrp.setGeometry(QRect(10, 320, 141, 61))
        self.clearGrp.setFont(font3)
        self.clearBtn = QPushButton(self.clearGrp)
        self.clearBtn.setObjectName(u"clearBtn")
        self.clearBtn.setGeometry(QRect(10, 30, 120, 24))
        icon4 = QIcon()
        icon4.addFile(u"assets/Icons/windowsClose.png", QSize(), QIcon.Normal, QIcon.Off)
        self.clearBtn.setIcon(icon4)
        self.clearBtn.setIconSize(QSize(24, 24))
        self.processedImg = QGroupBox(self.centralwidget)
        self.processedImg.setObjectName(u"processedImg")
        self.processedImg.setGeometry(QRect(740, 90, 551, 411))
        self.processedImg.setFont(font4)
        self.processedImgDIsplay = QLabel(self.processedImg)
        self.processedImgDIsplay.setObjectName(u"processedImgDIsplay")
        self.processedImgDIsplay.setGeometry(QRect(10, 30, 531, 371))
        self.processedImgDIsplay.setPixmap(QPixmap(u"Icons/noImageAvailable.png"))
        self.processedImgDIsplay.setScaledContents(True)
        self.line_5 = QFrame(self.centralwidget)
        self.line_5.setObjectName(u"line_5")
        self.line_5.setGeometry(QRect(1293, 90, 20, 521))
        self.line_5.setFrameShape(QFrame.VLine)
        self.line_5.setFrameShadow(QFrame.Sunken)
        self.groupBox = QGroupBox(self.centralwidget)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(1310, 90, 221, 80))
        self.groupBox.setFont(font4)
        self.timeDisplay = QLabel(self.groupBox)
        self.timeDisplay.setObjectName(u"timeDisplay")
        self.timeDisplay.setGeometry(QRect(10, 30, 201, 41))
        self.timeDisplay.setStyleSheet(u"background-color: rgb(229, 229, 229);")
        self.groupBox_2 = QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(1300, 0, 111, 80))
        font5 = QFont()
        font5.setFamilies([u"Consolas"])
        font5.setPointSize(12)
        font5.setBold(True)
        font5.setItalic(False)
        self.groupBox_2.setFont(font5)
        self.datetime = QLabel(self.groupBox_2)
        self.datetime.setObjectName(u"datetime")
        self.datetime.setGeometry(QRect(10, 30, 91, 41))
        font6 = QFont()
        font6.setFamilies([u"Consolas"])
        font6.setPointSize(12)
        font6.setBold(False)
        font6.setItalic(False)
        self.datetime.setFont(font6)
        self.datetime.setStyleSheet(u"background-color: rgb(229, 229, 229);")
        self.dia = QGroupBox(self.centralwidget)
        self.dia.setObjectName(u"dia")
        self.dia.setGeometry(QRect(1310, 320, 101, 61))
        self.dia.setFont(font3)
        self.plainTextEdit = QPlainTextEdit(self.dia)
        self.plainTextEdit.setObjectName(u"plainTextEdit")
        self.plainTextEdit.setGeometry(QRect(10, 20, 81, 31))
        self.plainTextEdit.setFont(font1)
        self.plainTextEdit.setStyleSheet(u"color: rgb(0, 255, 0);\n"
"background-color: rgb(229, 229, 229);")
        self.plainTextEdit.setLineWidth(0)
        self.plainTextEdit.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.plainTextEdit.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.coordinates = QGroupBox(self.centralwidget)
        self.coordinates.setObjectName(u"coordinates")
        self.coordinates.setGeometry(QRect(1310, 170, 201, 151))
        font7 = QFont()
        font7.setPointSize(9)
        font7.setBold(True)
        self.coordinates.setFont(font7)
        self.groupBox_4 = QGroupBox(self.coordinates)
        self.groupBox_4.setObjectName(u"groupBox_4")
        self.groupBox_4.setGeometry(QRect(10, 20, 81, 61))
        self.groupBox_4.setFont(font3)
        self.top = QLabel(self.groupBox_4)
        self.top.setObjectName(u"top")
        self.top.setGeometry(QRect(10, 30, 61, 16))
        font8 = QFont()
        font8.setFamilies([u"Consolas"])
        font8.setPointSize(9)
        font8.setBold(False)
        self.top.setFont(font8)
        self.top.setStyleSheet(u"background-color: rgb(229, 229, 229);")
        self.groupBox_5 = QGroupBox(self.coordinates)
        self.groupBox_5.setObjectName(u"groupBox_5")
        self.groupBox_5.setGeometry(QRect(100, 20, 81, 61))
        self.groupBox_5.setFont(font3)
        self.bottom = QLabel(self.groupBox_5)
        self.bottom.setObjectName(u"bottom")
        self.bottom.setGeometry(QRect(10, 30, 61, 16))
        self.bottom.setFont(font8)
        self.bottom.setStyleSheet(u"background-color: rgb(229, 229, 229);")
        self.groupBox_6 = QGroupBox(self.coordinates)
        self.groupBox_6.setObjectName(u"groupBox_6")
        self.groupBox_6.setGeometry(QRect(10, 80, 81, 61))
        self.groupBox_6.setFont(font3)
        self.left = QLabel(self.groupBox_6)
        self.left.setObjectName(u"left")
        self.left.setGeometry(QRect(10, 30, 61, 20))
        self.left.setFont(font8)
        self.left.setStyleSheet(u"background-color: rgb(229, 229, 229);")
        self.groupBox_7 = QGroupBox(self.coordinates)
        self.groupBox_7.setObjectName(u"groupBox_7")
        self.groupBox_7.setGeometry(QRect(100, 80, 81, 61))
        self.groupBox_7.setFont(font3)
        self.right = QLabel(self.groupBox_7)
        self.right.setObjectName(u"right")
        self.right.setGeometry(QRect(10, 30, 61, 16))
        self.right.setFont(font8)
        self.right.setStyleSheet(u"background-color: rgb(229, 229, 229);")
        self.groupBox_9 = QGroupBox(self.centralwidget)
        self.groupBox_9.setObjectName(u"groupBox_9")
        self.groupBox_9.setGeometry(QRect(1310, 380, 101, 61))
        self.groupBox_9.setFont(font3)
        self.Radius = QPlainTextEdit(self.groupBox_9)
        self.Radius.setObjectName(u"Radius")
        self.Radius.setGeometry(QRect(10, 20, 81, 31))
        self.Radius.setFont(font1)
        self.Radius.setStyleSheet(u"color: rgb(0, 255, 0);\n"
"background-color: rgb(229, 229, 229);")
        self.Radius.setLineWidth(0)
        self.Radius.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.Radius.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.groupBox_8 = QGroupBox(self.centralwidget)
        self.groupBox_8.setObjectName(u"groupBox_8")
        self.groupBox_8.setGeometry(QRect(170, 610, 561, 61))
        self.groupBox_8.setFont(font1)
        self.FilePath = QTextBrowser(self.groupBox_8)
        self.FilePath.setObjectName(u"FilePath")
        self.FilePath.setGeometry(QRect(10, 30, 541, 20))
        font9 = QFont()
        font9.setFamilies([u"Consolas"])
        font9.setPointSize(11)
        font9.setBold(False)
        self.FilePath.setFont(font9)
        self.FilePath.setStyleSheet(u"color: rgb(0, 0, 127);\n"
"background-color: rgb(238, 238, 238);")
        self.FilePath.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.FilePath.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.FilePath.setTabChangesFocus(True)
        self.groupBox_10 = QGroupBox(self.centralwidget)
        self.groupBox_10.setObjectName(u"groupBox_10")
        self.groupBox_10.setGeometry(QRect(1410, 320, 101, 61))
        self.groupBox_10.setFont(font3)
        self.ID = QPlainTextEdit(self.groupBox_10)
        self.ID.setObjectName(u"ID")
        self.ID.setGeometry(QRect(10, 20, 81, 31))
        self.ID.setFont(font1)
        self.ID.setStyleSheet(u"color: rgb(255, 0, 0);\n"
"background-color: rgb(229, 229, 229);")
        self.groupBox_11 = QGroupBox(self.centralwidget)
        self.groupBox_11.setObjectName(u"groupBox_11")
        self.groupBox_11.setGeometry(QRect(1410, 380, 101, 61))
        self.groupBox_11.setFont(font3)
        self.IR = QPlainTextEdit(self.groupBox_11)
        self.IR.setObjectName(u"IR")
        self.IR.setGeometry(QRect(10, 20, 81, 31))
        self.IR.setFont(font1)
        self.IR.setStyleSheet(u"color: rgb(255, 0, 0);\n"
"background-color: rgb(229, 229, 229);")
        self.FSOriginal = QPushButton(self.centralwidget)
        self.FSOriginal.setObjectName(u"FSOriginal")
        self.FSOriginal.setGeometry(QRect(170, 510, 161, 31))
        self.FSOriginal.setFont(font1)
        icon5 = QIcon()
        icon5.addFile(u"assets/Icons/windowsFS.png", QSize(), QIcon.Normal, QIcon.Off)
        self.FSOriginal.setIcon(icon5)
        self.FSOriginal.setIconSize(QSize(30, 30))
        self.FSProcessed = QPushButton(self.centralwidget)
        self.FSProcessed.setObjectName(u"FSProcessed")
        self.FSProcessed.setGeometry(QRect(740, 510, 161, 31))
        self.FSProcessed.setFont(font1)
        self.FSProcessed.setIcon(icon5)
        self.FSProcessed.setIconSize(QSize(30, 30))
        self.groupBox_12 = QGroupBox(self.centralwidget)
        self.groupBox_12.setObjectName(u"groupBox_12")
        self.groupBox_12.setGeometry(QRect(10, 380, 141, 61))
        self.groupBox_12.setFont(font3)
        self.history = QPushButton(self.groupBox_12)
        self.history.setObjectName(u"history")
        self.history.setGeometry(QRect(10, 30, 120, 24))
        self.history.setFont(font3)
        icon6 = QIcon()
        icon6.addFile(u"assets/Icons/icons8-history-50.png", QSize(), QIcon.Normal, QIcon.Off)
        self.history.setIcon(icon6)
        self.history.setIconSize(QSize(24, 24))
        self.Thicknes = QGroupBox(self.centralwidget)
        self.Thicknes.setObjectName(u"Thicknes")
        self.Thicknes.setGeometry(QRect(1310, 440, 101, 61))
        self.Thicknes.setFont(font3)
        self.thick = QPlainTextEdit(self.Thicknes)
        self.thick.setObjectName(u"thick")
        self.thick.setGeometry(QRect(10, 20, 81, 31))
        self.thick.setFont(font1)
        self.thick.setStyleSheet(u"color: rgb(0, 0, 255);\n"
"background-color: rgb(229, 229, 229);")
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 5, 301, 71))
        self.label.setPixmap(QPixmap(u"Icons/bitmap_logo.bmp"))
        self.groupBox_13 = QGroupBox(self.centralwidget)
        self.groupBox_13.setObjectName(u"groupBox_13")
        self.groupBox_13.setGeometry(QRect(1410, 440, 101, 61))
        self.groupBox_13.setFont(font3)
        self.center = QPlainTextEdit(self.groupBox_13)
        self.center.setObjectName(u"center")
        self.center.setGeometry(QRect(0, 20, 101, 31))
        self.center.setFont(font9)
        self.center.setStyleSheet(u"background-color: rgb(229, 229, 229);\n"
"color: rgb(120, 0, 172);")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1920, 25))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.actiondate.setText(QCoreApplication.translate("MainWindow", u"date", None))
        self.Tools.setTitle(QCoreApplication.translate("MainWindow", u"Tools", None))
        self.squareBox.setText("")
        self.boundingBoxLabel.setText(QCoreApplication.translate("MainWindow", u"Bounding Box", None))
        self.rhombusBoxLabel.setText(QCoreApplication.translate("MainWindow", u"Rhombus Box", None))
        self.rhombusBox.setText("")
        self.findCenter.setText(QCoreApplication.translate("MainWindow", u"Find Center", None))
        self.cntrBtn.setText("")
        self.OrgImg.setTitle(QCoreApplication.translate("MainWindow", u"Original Image", None))
        self.orgImageDisp.setText("")
        self.groupBox_3.setTitle(QCoreApplication.translate("MainWindow", u"Select Image", None))
        self.loadFile.setText(QCoreApplication.translate("MainWindow", u"Image", None))
        self.clearGrp.setTitle(QCoreApplication.translate("MainWindow", u"Clear Original Image", None))
        self.clearBtn.setText(QCoreApplication.translate("MainWindow", u"Clear", None))
        self.processedImg.setTitle(QCoreApplication.translate("MainWindow", u"Processed Image", None))
        self.processedImgDIsplay.setText("")
        self.groupBox.setTitle(QCoreApplication.translate("MainWindow", u"Time Taken", None))
        self.timeDisplay.setText("")
        self.groupBox_2.setTitle(QCoreApplication.translate("MainWindow", u"Date", None))
        self.datetime.setText("")
        self.dia.setTitle(QCoreApplication.translate("MainWindow", u"Outer Diameter", None))
        self.coordinates.setTitle(QCoreApplication.translate("MainWindow", u"Co-Ordinates", None))
        self.groupBox_4.setTitle(QCoreApplication.translate("MainWindow", u"Top", None))
        self.top.setText("")
        self.groupBox_5.setTitle(QCoreApplication.translate("MainWindow", u"Bottom", None))
        self.bottom.setText("")
        self.groupBox_6.setTitle(QCoreApplication.translate("MainWindow", u"Left", None))
        self.left.setText("")
        self.groupBox_7.setTitle(QCoreApplication.translate("MainWindow", u"Right", None))
        self.right.setText("")
        self.groupBox_9.setTitle(QCoreApplication.translate("MainWindow", u"Outer Radius", None))
        self.groupBox_8.setTitle(QCoreApplication.translate("MainWindow", u"File Path", None))
        self.groupBox_10.setTitle(QCoreApplication.translate("MainWindow", u"Internal Dia", None))
        self.groupBox_11.setTitle(QCoreApplication.translate("MainWindow", u"Internal Radius", None))
        self.FSOriginal.setText(QCoreApplication.translate("MainWindow", u"Full Screen", None))
        self.FSProcessed.setText(QCoreApplication.translate("MainWindow", u"Full Screen", None))
        self.groupBox_12.setTitle(QCoreApplication.translate("MainWindow", u"History", None))
        self.history.setText(QCoreApplication.translate("MainWindow", u"LOG File", None))
        self.Thicknes.setTitle(QCoreApplication.translate("MainWindow", u"Thickness", None))
        self.label.setText("")
        self.groupBox_13.setTitle(QCoreApplication.translate("MainWindow", u"Center", None))
    # retranslateUi

