# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'form.ui'
##
## Created by: Qt User Interface Compiler version 6.6.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QGroupBox, QLabel,
    QMainWindow, QMenuBar, QPlainTextEdit, QPushButton,
    QSizePolicy, QStatusBar, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1920, 1080)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.line = QFrame(self.centralwidget)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(0, 90, 1920, 3))
        self.line.setFrameShape(QFrame.HLine)
        self.line.setFrameShadow(QFrame.Sunken)
        self.line_2 = QFrame(self.centralwidget)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setGeometry(QRect(150, 90, 20, 981))
        self.line_2.setFrameShape(QFrame.VLine)
        self.line_2.setFrameShadow(QFrame.Sunken)
        self.groupBox = QGroupBox(self.centralwidget)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(10, 100, 141, 321))
        font = QFont()
        font.setPointSize(10)
        font.setBold(False)
        self.groupBox.setFont(font)
        self.select = QPushButton(self.groupBox)
        self.select.setObjectName(u"select")
        self.select.setGeometry(QRect(10, 30, 121, 24))
        font1 = QFont()
        font1.setFamilies([u"Sans Serif Collection"])
        font1.setPointSize(10)
        font1.setBold(False)
        self.select.setFont(font1)
        self.process = QPushButton(self.groupBox)
        self.process.setObjectName(u"process")
        self.process.setGeometry(QRect(10, 90, 121, 24))
        self.process.setFont(font1)
        self.extract = QPushButton(self.groupBox)
        self.extract.setObjectName(u"extract")
        self.extract.setGeometry(QRect(10, 150, 121, 24))
        self.extract.setFont(font1)
        self.match = QPushButton(self.groupBox)
        self.match.setObjectName(u"match")
        self.match.setGeometry(QRect(10, 210, 121, 24))
        self.match.setFont(font1)
        self.clear = QPushButton(self.groupBox)
        self.clear.setObjectName(u"clear")
        self.clear.setGeometry(QRect(10, 270, 121, 24))
        self.clear.setFont(font1)
        self.groupBox_2 = QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(170, 90, 441, 251))
        self.selectedFrame = QLabel(self.groupBox_2)
        self.selectedFrame.setObjectName(u"selectedFrame")
        self.selectedFrame.setGeometry(QRect(10, 30, 421, 211))
        self.selectedFrame.setScaledContents(True)
        self.groupBox_3 = QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(610, 90, 441, 251))
        self.gray_image = QLabel(self.groupBox_3)
        self.gray_image.setObjectName(u"gray_image")
        self.gray_image.setGeometry(QRect(10, 30, 421, 211))
        self.gray_image.setScaledContents(True)
        self.groupBox_4 = QGroupBox(self.centralwidget)
        self.groupBox_4.setObjectName(u"groupBox_4")
        self.groupBox_4.setGeometry(QRect(1050, 90, 441, 251))
        self.edge = QLabel(self.groupBox_4)
        self.edge.setObjectName(u"edge")
        self.edge.setGeometry(QRect(10, 30, 421, 211))
        self.edge.setScaledContents(True)
        self.groupBox_5 = QGroupBox(self.centralwidget)
        self.groupBox_5.setObjectName(u"groupBox_5")
        self.groupBox_5.setGeometry(QRect(170, 340, 441, 251))
        self.threshold = QLabel(self.groupBox_5)
        self.threshold.setObjectName(u"threshold")
        self.threshold.setGeometry(QRect(10, 30, 421, 211))
        self.threshold.setScaledContents(True)
        self.groupBox_6 = QGroupBox(self.centralwidget)
        self.groupBox_6.setObjectName(u"groupBox_6")
        self.groupBox_6.setGeometry(QRect(610, 340, 441, 251))
        self.np = QLabel(self.groupBox_6)
        self.np.setObjectName(u"np")
        self.np.setGeometry(QRect(10, 30, 421, 211))
        self.np.setScaledContents(True)
        self.groupBox_7 = QGroupBox(self.centralwidget)
        self.groupBox_7.setObjectName(u"groupBox_7")
        self.groupBox_7.setGeometry(QRect(1050, 340, 441, 251))
        self.Extract_det = QPlainTextEdit(self.groupBox_7)
        self.Extract_det.setObjectName(u"Extract_det")
        self.Extract_det.setGeometry(QRect(10, 30, 421, 211))
        font2 = QFont()
        font2.setFamilies([u"Sans Serif Collection"])
        font2.setPointSize(20)
        font2.setBold(True)
        self.Extract_det.setFont(font2)
        self.Extract_det.setStyleSheet(u"color: rgb(255, 0, 0);\n"
"background-color: rgb(240, 240, 240);")
        self.line_3 = QFrame(self.centralwidget)
        self.line_3.setObjectName(u"line_3")
        self.line_3.setGeometry(QRect(160, 600, 1761, 16))
        self.line_3.setFrameShape(QFrame.HLine)
        self.line_3.setFrameShadow(QFrame.Sunken)
        self.groupBox_8 = QGroupBox(self.centralwidget)
        self.groupBox_8.setObjectName(u"groupBox_8")
        self.groupBox_8.setGeometry(QRect(170, 610, 641, 131))
        self.matched = QPlainTextEdit(self.groupBox_8)
        self.matched.setObjectName(u"matched")
        self.matched.setGeometry(QRect(10, 30, 621, 91))
        self.matched.setStyleSheet(u"background-color: rgb(240, 240, 240);")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1920, 21))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.groupBox.setTitle(QCoreApplication.translate("MainWindow", u"Operations", None))
        self.select.setText(QCoreApplication.translate("MainWindow", u"Select Image", None))
        self.process.setText(QCoreApplication.translate("MainWindow", u"Process Image", None))
        self.extract.setText(QCoreApplication.translate("MainWindow", u"Extract Plate", None))
        self.match.setText(QCoreApplication.translate("MainWindow", u"Match Plate Details", None))
        self.clear.setText(QCoreApplication.translate("MainWindow", u"Clear ", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("MainWindow", u"Selected Image", None))
        self.selectedFrame.setText("")
        self.groupBox_3.setTitle(QCoreApplication.translate("MainWindow", u" Processed Image 1(gray)", None))
        self.gray_image.setText("")
        self.groupBox_4.setTitle(QCoreApplication.translate("MainWindow", u"Processed Image 2 (edge)", None))
        self.edge.setText("")
        self.groupBox_5.setTitle(QCoreApplication.translate("MainWindow", u"Processed Image 3(Threshold)", None))
        self.threshold.setText("")
        self.groupBox_6.setTitle(QCoreApplication.translate("MainWindow", u"Final Image(Number Plate)", None))
        self.np.setText("")
        self.groupBox_7.setTitle(QCoreApplication.translate("MainWindow", u"Extracted Number plate", None))
        self.groupBox_8.setTitle(QCoreApplication.translate("MainWindow", u"Matched Plate Details", None))
    # retranslateUi

